### ISSUE TITLE
Transaction Initiation endpoint returning 404

### ISSUE THREAD

**Issue by Owoade** [LazerPay-Finance/lazerpay-status#25]
**Describe the bug**
The payment initiation endpoint returning 404

**To Reproduce**
1. Go to https://api.lazerpay.engineering/api/v1/transaction/initialize

**Note** The request was sent with the right request type, payload and headers. 

**Expected behavior**
The server returns the response object below.
{
  "statusCode": 404,
  "message": "Cannot POST /api/v1/transaction/initialize%20",
  "error": "Not Found"
}

**Comment by iamnotstatic** [comment]
> 1. https://api.lazerpay.engineering/api/v1/transaction/initialize

Hi @Owoade 

Looking at the error response the additional characters `Cannot POST /api/v1/transaction/initialize%20` added is why you got the 404 error. 

Can you try making a call without the additional characters

**Comment by Owoade** [comment]
Thanks, the fault was mine. It worked perfectly.  Unrelated, but I recently published a ruby SDK for lazerpay API https://rubygems.org/gems/lazerpay 

docs https://github.com/Owoade/lazerpay-ruby-sdk#readme

Though, there are some finishing touches to be applied but in no time I'll have it completed.

Thanks in anticipation as I await your review.
